<?php

namespace GoPay\Definition\Payment;

class BankSwiftCode
{
    const CESKA_SPORITELNA = 'GIBACZPX';
    const KOMERCNI_BANKA = 'KOMBCZPP';
    const RAIFFEISENBANK = 'RZBCCZPP';
    const MBANK = 'BREXCZPP';
    const FIO_BANKA = 'FIOBCZPP';
    const CSOB = 'CEKOCZPP';
    const ERA = 'CEKOCZPP-ERA';
    const UNICREDIT_BANK_CZ = 'BACXCZPP';
    const VSEOBECNA_VEROVA_BANKA_BANKA = 'SUBASKBX';
    const TATRA_BANKA = 'TATRSKBX';
    const UNICREDIT_BANK_SK = 'UNCRSKBX';
    const SLOVENSKA_SPORITELNA = 'GIBASKBX';
    const POSTOVA_BANKA = 'POBNSKBA';
    const CSOB_SK = 'CEKOSKBX';
    const SBERBANK_SLOVENSKO = 'LUBASKBX';
    const SPECIAL = 'OTHERS';
    const MBANK1 = 'BREXPLPW';
    const CITI_HANDLOWY = 'CITIPLPX';
    const IKO = 'BPKOPLPW-IKO';
    const INTELIGO = 'BPKOPLPW-INTELIGO';
    const PLUS_BANK = 'IVSEPLPP';
    const BANK_BPH_SA = 'BPHKPLPK';
    const TOYOTA_BANK = 'TOBAPLPW';
    const VOLKSWAGEN_BANK = 'VOWAPLP1';
    const SGB = 'GBWCPLPP';
    const POCZTOWY_BANK = 'POCZPLP4';
    const BGZ_BANK = 'GOPZPLPW';
    const IDEA = 'IEEAPLPA';
    const BPS = 'POLUPLPR';
    const GETIN_ONLINE = 'GBGCPLPK-GIO';
    const BLIK = 'GBGCPLPK-BLIK';
    const NOBLE_BANK = 'GBGCPLPK-NOB';
    const ORANGE = 'BREXPLPW-OMB';
    const BZ_WBK = 'WBKPPLPP';
    const RAIFFEISEN_BANK_POLSKA_SA = 'RCBWPLPW';
    const POWSZECHNA_KASA_OSZCZEDNOSCI_BANK_POLSKI_SA = 'BPKOPLPW';
    const ALIOR_BANK = 'ALBPPLPW';
    const ING_BANK_SLASKI = 'INGBPLPW';
    const PEKAO_SA = 'PKOPPLPW';
    const GETIN_ONLINE1 = 'GBGCPLPK';
    const BANK_MILLENNIUM = 'BIGBPLPW';
    const BANK_OCHRONY_SRODOWISKA = 'EBOSPLPW';
    const BNP_PARIBAS_POLSKA = 'PPABPLPK';
    const CREDIT_AGRICOLE = 'AGRIPLPR';
    const DEUTSCHE_BANK_POLSKA_SA = 'DEUTPLPX';
    const DNB_NORD = 'DNBANOKK';
    const E_SKOK = 'NBPLPLPW';
    const EUROBANK = 'SOGEPLPW';
    const POLSKI_BANK_PRZEDSIEBIORCZOSCI_SPOLKA_AKCYJNA = 'PBPBPLPW';
}
