<?php

namespace GoPay\Definition\Payment;

class BankSwiftCode
{
    // CZ
    const CESKA_SPORITELNA = 'GIBACZPX';
    const KOMERCNI_BANKA = 'KOMBCZPP';
    const CSOB = 'CEKOCZPP';
    const RAIFFEISENBANK = 'RZBCCZPP';
    const UNICREDIT_BANK_CZ = 'BACXCZPP';
    const MONETA_MONEY_BANK = 'AGBACZPP';
    const FIO_BANKA = 'FIOBCZPP';
    const MBANK = 'BREXCZPP';
    const AIRBANK = 'AIRACZPP';
    const ING_BANK = 'INGBCZPP';
    const OBERBANK = 'OBKLCZ2X';
    const VUB_PRAHA = 'SUBACZPP';
    const HELLO_BANK = 'BPPFCZP1';
    const CREDITAS = 'CTASCZ22';
    const MAX_BANKA = 'EXPNCZPP';
    const JT_BANKA = 'JTBPCZPP';
    //SK
    const TATRA_BANKA = 'TATRSKBX';
    const VSEOBECNA_UVEROVA_BANKA = 'SUBASKBX';
    const UNICREDIT_BANK_SK = 'UNCRSKBX';
    const SLOVENSKA_SPORITELNA = 'GIBASKBX';
    const CSOB_SK = 'CEKOSKBX';
    const POSTOVA_BANKA = 'POBNSKBA';
    const OTP_BANKA_SLOVENSKO = 'OTPVSKBX';
    const PRIMA_BANKA_SLOVENSKO = 'KOMASK2X';
    const CITIBANK_EUROPE = 'CITISKBA';
    const FIO_BANKA_SK = 'FIOZSKBA';
    const MBANK_SK = 'BREXSKBX';
    const ING_BANK_SK = 'INGBSKBX';
    const JT_BANKA_SK = 'JTBPSKBA';
    const OBERBANK_SK = 'OBKLSKBA';
    const PRIVATBANKA = 'BSLOSK22';
    const BKS_BANK = 'BFKKSKBB';
    const RAIFFEISENBANK_SK = 'TATRSKBXXXX';
    const KOMERCNI_BANKA_SK = 'KOMBSKBA';
    // PL
    const MBANK1 = 'BREXPLPW';
    const CITI_HANDLOWY = 'CITIPLPX';
    const IKO = 'BPKOPLPW-IKO';
    const INTELIGO = 'BPKOPLPW-INTELIGO';
    const PLUS_BANK = 'IVSEPLPP';
    const BANK_BPH_SA = 'BPHKPLPK';
    const TOYOTA_BANK = 'TOBAPLPW';
    const VOLKSWAGEN_BANK = 'VOWAPLP1';
    const SGB = 'GBWCPLPP';
    const POCZTOWY_BANK = 'POCZPLP4';
    const BGZ_BANK = 'GOPZPLPW';
    const IDEA = 'IEEAPLPA';
    const BPS = 'POLUPLPR';
    const GETIN_ONLINE = 'GBGCPLPK-GIO';
    const BLIK = 'GBGCPLPK-BLIK';
    const NOBLE_BANK = 'GBGCPLPK-NOB';
    const ORANGE = 'BREXPLPW-OMB';
    const BZ_WBK = 'WBKPPLPP';
    const RAIFFEISEN_BANK_POLSKA_SA = 'RCBWPLPW';
    const POWSZECHNA_KASA_OSZCZEDNOSCI_BANK_POLSKI_SA = 'BPKOPLPW';
    const ALIOR_BANK = 'ALBPPLPW';
    const ING_BANK_SLASKI = 'INGBPLPW';
    const PEKAO_SA = 'PKOPPLPW';
    const GETIN_ONLINE1 = 'GBGCPLPK';
    const BANK_MILLENNIUM = 'BIGBPLPW';
    const BANK_OCHRONY_SRODOWISKA = 'EBOSPLPW';
    const BNP_PARIBAS_POLSKA = 'PPABPLPK';
    const CREDIT_AGRICOLE = 'AGRIPLPR';
    const DEUTSCHE_BANK_POLSKA_SA = 'DEUTPLPX';
    const DNB_NORD = 'DNBANOKK';
    const E_SKOK = 'NBPLPLPW';
    const EUROBANK = 'SOGEPLPW';
    const POLSKI_BANK_PRZEDSIEBIORCZOSCI_SPOLKA_AKCYJNA = 'PBPBPLPW';
    // Others
    const SPECIAL = 'OTHERS';
}
